### PR TITLE
Use getIconName for tab icon if it exists

### PR DESCRIPTION
**Pull request by piascikj**
I wanted exposé to work with imdone-atom tabs and this seemed like the most future-proof way to do it.  By the way, this is a great package!

### CODE REVIEW

**Comment by mrodalgaard** [comment]
Thank you.

**Comment by piascikj** [comment]
np. thanks for merging!  Any idea when you might release?

**Comment by mrodalgaard** [comment]
Now :)

**Comment by piascikj** [comment]
Sweet, thanks!

**Pull request merged**
